stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
   paths:
     - .gradle/wrapper
     - .gradle/caches

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
