package ru.pearx.carbide.mc;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import net.minecraftforge.fml.relauncher.Side;
import org.apache.logging.log4j.Logger;
import ru.pearx.carbide.mc.common.CommonProxy;
import ru.pearx.carbide.mc.common.PXLCapabilities;
import ru.pearx.carbide.mc.common.networking.packets.CPacketOpenStructureCreationGui;
import ru.pearx.carbide.mc.common.networking.packets.CPacketSyncASMState;
import ru.pearx.carbide.mc.common.networking.packets.CPacketUpdateTileEntitySyncable;
import ru.pearx.carbide.mc.common.networking.packets.SPacketCreateStructure;
import ru.pearx.carbide.mc.common.structure.CommandStructure;
import ru.pearx.carbide.mc.common.structure.processors.LootProcessor;
import ru.pearx.carbide.mc.common.structure.processors.StructureProcessor;
import ru.pearx.carbide.mc.common.tiles.PXLTiles;

import java.util.Collections;

/*
 * Created by mrAppleXZ on 10.07.17 21:39.
 */
@Mod(modid = CarbideMC.MODID, version = CarbideMC.VERSION, acceptedMinecraftVersions = "", name = CarbideMC.NAME)
public class CarbideMC
{
    public static final String NAME = "Carbide";
    public static final String MODID = "carbide";
    public static final String VERSION = "@VERSION@";

    @SidedProxy(clientSide = "ru.pearx.carbide.mc.client.ClientProxy", serverSide = "ru.pearx.carbide.mc.server.ServerProxy")
    public static CommonProxy PROXY;

    public static final SimpleNetworkWrapper NETWORK = NetworkRegistry.INSTANCE.newSimpleChannel(MODID);
    private static Logger log;

    @Mod.EventHandler
    public static void preInit(FMLPreInitializationEvent e)
    {
        ModMetadata data = e.getModMetadata();
        data.url = "https://minecraft.curseforge.com/projects/carbide";
        data.authorList = Collections.singletonList("mrAppleXZ");
        data.autogenerated = false;
        data.description = "A common library for all MC mods by PearX Team.";
        data.version = VERSION;
        data.modId = MODID;
        data.name = NAME;

        log = e.getModLog();

        PXLCapabilities.register();
        PXLTiles.setup();

        StructureProcessor.REGISTRY.register(new LootProcessor());

        PROXY.preInit();
    }

    @Mod.EventHandler
    public static void init(FMLInitializationEvent e)
    {
        int id = 0;
        NETWORK.registerMessage(CPacketSyncASMState.Handler.class, CPacketSyncASMState.class, id++, Side.CLIENT);
        NETWORK.registerMessage(CPacketOpenStructureCreationGui.Handler.class, CPacketOpenStructureCreationGui.class, id++, Side.CLIENT);
        NETWORK.registerMessage(SPacketCreateStructure.Handler.class, SPacketCreateStructure.class, id++, Side.SERVER);
        NETWORK.registerMessage(CPacketUpdateTileEntitySyncable.Handler.class, CPacketUpdateTileEntitySyncable.class, id++, Side.CLIENT);
    }

    @Mod.EventHandler
    public static void onServerStart(FMLServerStartingEvent e)
    {
        e.registerServerCommand(new CommandStructure());
        //this is there to allow developers to disable the online mode for LAN worlds by force
        if(System.getProperties().containsKey("ru.pearx.carbide.mc.force-offline-mode"))
            e.getServer().setOnlineMode(false);
    }

    public static Logger getLog()
    {
        return log;
    }
}
